services:
  - type: web
    name: foaie-parcurs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LOCATIONIQ_KEY
        sync: false
      - key: CONTACT_EMAIL
        sync: false
